import type { ResourceDefinition } from './resourceDefinition.js';

/**
 * Ressources naturelles de la V1.
 *
 * Rien ici ne décrit un usage : une définition dit ce qu'une chose **est** et où elle
 * pousse, jamais ce qu'un humain peut en faire ni ce qu'il en sait. Le silex est décrit
 * comme une pierre rare des zones rocheuses ; qu'il puisse produire un éclat tranchant
 * sera une découverte, pas une propriété déclarée ici.
 */
export const DEFAULT_RESOURCES: readonly ResourceDefinition[] = [
  {
    id: 'tree_broadleaf',
    displayName: 'Arbre à feuilles',
    category: 'tree',
    visual: {
      shape: 'broadleaf_tree',
      primaryColor: '#4a6b32',
      secondaryColor: '#6b5238',
      heightM: 7.5,
      radiusM: 2.6,
      scaleVariance: 0.35,
      detailOnly: false,
      deciduous: true,
    },
    density: 0.62,
    rarity: 1,
    spacingMeters: 5.5,
    clustering: 0.65,
    clusterScaleMeters: 90,
    biomeWeights: { forest: 1, sparse_forest: 0.45, grassland: 0.06, riverbank: 0.2, wetland: 0.1 },
    slope: { min: 0, max: 0.32, tolerance: 0.18 },
    fertility: { min: 0.35, max: 1, tolerance: 0.25 },
    moisture: { min: 0.4, max: 1, tolerance: 0.25 },
    elevation: { min: 0.34, max: 0.76, tolerance: 0.12 },
    interactive: true,
    // Un arbre abattu ne repousse pas au même endroit — pas d'écologie annuelle de
    // repeuplement forestier pour l'instant, seulement le renouvellement du vivant.
    renewalMode: 'none',
  },
  {
    id: 'tree_conifer',
    displayName: 'Conifère',
    category: 'tree',
    visual: {
      shape: 'conifer_tree',
      primaryColor: '#2f5138',
      secondaryColor: '#5b4630',
      heightM: 9.5,
      radiusM: 2.1,
      scaleVariance: 0.3,
      detailOnly: false,
    },
    density: 0.5,
    rarity: 1,
    spacingMeters: 5,
    clustering: 0.7,
    clusterScaleMeters: 120,
    biomeWeights: { forest: 0.8, sparse_forest: 0.4, rocky: 0.25 },
    slope: { min: 0, max: 0.45, tolerance: 0.2 },
    temperature: { min: 0, max: 0.62, tolerance: 0.2 },
    elevation: { min: 0.48, max: 0.9, tolerance: 0.18 },
    interactive: true,
    renewalMode: 'none',
  },
  {
    id: 'bush',
    displayName: 'Buisson',
    category: 'shrub',
    visual: {
      shape: 'bush',
      primaryColor: '#5c7d3f',
      heightM: 1.1,
      radiusM: 0.85,
      scaleVariance: 0.4,
      detailOnly: false,
    },
    density: 0.32,
    rarity: 1,
    spacingMeters: 3.2,
    clustering: 0.45,
    clusterScaleMeters: 55,
    biomeWeights: {
      grassland: 0.7,
      sparse_forest: 1,
      forest: 0.55,
      riverbank: 0.5,
      wetland: 0.35,
      rocky: 0.15,
    },
    slope: { min: 0, max: 0.4, tolerance: 0.2 },
    moisture: { min: 0.2, max: 1, tolerance: 0.2 },
    interactive: true,
    // Sans propriété alimentaire : ce qu'on y prélève (bois, fibre) ne repousse pas
    // au même endroit, contrairement à un buisson à baies.
    renewalMode: 'none',
  },
  {
    id: 'berry_bush',
    displayName: 'Buisson à baies',
    category: 'shrub',
    visual: {
      shape: 'bush',
      primaryColor: '#4f7040',
      secondaryColor: '#a83246',
      heightM: 1,
      radiusM: 0.8,
      scaleVariance: 0.3,
      detailOnly: false,
    },
    density: 0.2,
    rarity: 0.35,
    spacingMeters: 4.5,
    clustering: 0.6,
    clusterScaleMeters: 40,
    biomeWeights: { sparse_forest: 1, grassland: 0.6, forest: 0.45, riverbank: 0.5 },
    slope: { min: 0, max: 0.3, tolerance: 0.18 },
    fertility: { min: 0.45, max: 1, tolerance: 0.22 },
    moisture: { min: 0.4, max: 0.9, tolerance: 0.2 },
    interactive: true,
    food: { nutritionKcal: 43, waterContent01: 0.85, toxicity01: 0 },
    // Un buisson porte plusieurs poignées de baies : trois visites avant qu'il soit nu.
    harvestServings: 3,
    // Plante vivante : de nouvelles baies poussent, que le buisson ait été vidé ou
    // seulement partiellement cueilli.
    renewalMode: 'regrowWhenDepleted',
  },
  {
    id: 'mushroom',
    displayName: 'Champignon',
    category: 'ground_cover',
    visual: {
      shape: 'mushroom',
      primaryColor: '#8a6a4b',
      secondaryColor: '#d9cbb2',
      heightM: 0.18,
      radiusM: 0.13,
      scaleVariance: 0.45,
      detailOnly: true,
    },
    density: 0.22,
    rarity: 0.5,
    spacingMeters: 2.2,
    clustering: 0.8,
    clusterScaleMeters: 22,
    biomeWeights: { forest: 1, sparse_forest: 0.4, wetland: 0.3 },
    moisture: { min: 0.65, max: 1, tolerance: 0.15 },
    slope: { min: 0, max: 0.3, tolerance: 0.15 },
    vegetation: { min: 0.5, max: 1, tolerance: 0.2 },
    interactive: true,
    // Toxicité réelle et non nulle : c'est la vérité du monde, pas ce qu'un humain en sait.
    food: { nutritionKcal: 22, waterContent01: 0.9, toxicity01: 0.45 },
    renewalMode: 'regrowWhenDepleted',
  },
  {
    id: 'stone',
    displayName: 'Pierre',
    category: 'stone',
    visual: {
      shape: 'boulder',
      primaryColor: '#8d8a84',
      heightM: 0.6,
      radiusM: 0.5,
      scaleVariance: 0.55,
      detailOnly: false,
    },
    density: 0.35,
    rarity: 1,
    spacingMeters: 3.6,
    clustering: 0.55,
    clusterScaleMeters: 60,
    biomeWeights: {
      rocky: 1,
      grassland: 0.12,
      sparse_forest: 0.14,
      forest: 0.1,
      riverbank: 0.3,
      wetland: 0.05,
    },
    rockiness: { min: 0.25, max: 1, tolerance: 0.3 },
    interactive: true,
    // Un minéral extrait ne repousse jamais, quelle que soit l'écologie locale.
    renewalMode: 'none',
  },
  {
    id: 'flint',
    displayName: 'Silex',
    category: 'stone',
    visual: {
      shape: 'shard',
      primaryColor: '#3f4247',
      heightM: 0.22,
      radiusM: 0.18,
      scaleVariance: 0.4,
      detailOnly: true,
    },
    density: 0.16,
    // Nettement plus rare que la pierre commune : il conditionnera les premiers outils.
    rarity: 0.12,
    spacingMeters: 6.5,
    clustering: 0.75,
    clusterScaleMeters: 45,
    biomeWeights: { rocky: 1, riverbank: 0.35, grassland: 0.05 },
    rockiness: { min: 0.5, max: 1, tolerance: 0.25 },
    elevation: { min: 0.45, max: 1, tolerance: 0.2 },
    interactive: true,
    renewalMode: 'none',
  },
  {
    id: 'dead_branch',
    displayName: 'Bois mort',
    category: 'debris',
    visual: {
      shape: 'branch',
      primaryColor: '#6a5439',
      heightM: 0.16,
      radiusM: 0.09,
      scaleVariance: 0.5,
      detailOnly: true,
    },
    density: 0.3,
    rarity: 0.6,
    spacingMeters: 3,
    clustering: 0.5,
    clusterScaleMeters: 70,
    biomeWeights: { forest: 1, sparse_forest: 0.6, rocky: 0.1, riverbank: 0.2 },
    vegetation: { min: 0.4, max: 1, tolerance: 0.25 },
    slope: { min: 0, max: 0.4, tolerance: 0.2 },
    interactive: true,
    // Une branche ramassée ne repousse pas — seul un nouveau bois mort tombé ailleurs
    // pourrait apparaître, ce que l'écologie ne simule pas encore.
    renewalMode: 'none',
  },
  {
    id: 'dry_grass',
    displayName: 'Herbe sèche',
    category: 'ground_cover',
    visual: {
      shape: 'tuft',
      primaryColor: '#9aa055',
      heightM: 0.42,
      radiusM: 0.22,
      scaleVariance: 0.5,
      detailOnly: true,
    },
    density: 0.34,
    rarity: 1,
    spacingMeters: 2.6,
    clustering: 0.4,
    clusterScaleMeters: 35,
    biomeWeights: { grassland: 1, sparse_forest: 0.4, rocky: 0.15, riverbank: 0.3 },
    moisture: { min: 0, max: 0.6, tolerance: 0.25 },
    slope: { min: 0, max: 0.35, tolerance: 0.2 },
    // Décor : généré et rendu, mais aucune mécanique ne le manipulera avant longtemps.
    interactive: false,
  },
  {
    id: 'reed',
    displayName: 'Roseau',
    category: 'ground_cover',
    visual: {
      shape: 'reed',
      primaryColor: '#7f9a4e',
      heightM: 1.4,
      radiusM: 0.16,
      scaleVariance: 0.35,
      detailOnly: true,
    },
    density: 0.45,
    rarity: 1,
    spacingMeters: 1.9,
    clustering: 0.6,
    clusterScaleMeters: 25,
    biomeWeights: { wetland: 1, riverbank: 0.8 },
    waterProximity: { min: 0.8, max: 1, tolerance: 0.12 },
    slope: { min: 0, max: 0.15, tolerance: 0.1 },
    interactive: false,
  },
  {
    id: 'hazel_bush',
    displayName: 'Noisetier',
    category: 'shrub',
    visual: {
      shape: 'bush',
      primaryColor: '#6a8a3a',
      secondaryColor: '#7a5a3a',
      heightM: 2.2,
      radiusM: 1.5,
      scaleVariance: 0.3,
      detailOnly: false,
      deciduous: true,
    },
    density: 0.18,
    // Moins commun que le buisson : sa présence signale une lisière exploitée par les
    // groupes humains, où la cueillette des noisettes sera une ressource alimentaire majeure.
    rarity: 0.3,
    spacingMeters: 4.8,
    clustering: 0.5,
    clusterScaleMeters: 45,
    biomeWeights: { sparse_forest: 1, riverbank: 0.7, forest: 0.35 },
    slope: { min: 0, max: 0.3, tolerance: 0.18 },
    fertility: { min: 0.5, max: 1, tolerance: 0.2 },
    moisture: { min: 0.35, max: 0.8, tolerance: 0.2 },
    interactive: true,
    // Graines sèches, riches en lipides : le stock d'énergie le plus dense du monde.
    food: { nutritionKcal: 628, waterContent01: 0.05, toxicity01: 0 },
    // Un noisetier porte assez de noisettes pour plusieurs cueillettes successives.
    harvestServings: 4,
    renewalMode: 'regrowWhenDepleted',
  },
  {
    id: 'willow',
    displayName: 'Saule',
    category: 'tree',
    visual: {
      shape: 'broadleaf_tree',
      primaryColor: '#5f7a63',
      secondaryColor: '#6b5b48',
      heightM: 5.5,
      radiusM: 1.8,
      scaleVariance: 0.3,
      detailOnly: false,
      deciduous: true,
    },
    density: 0.28,
    rarity: 0.5,
    spacingMeters: 4.5,
    clustering: 0.45,
    clusterScaleMeters: 60,
    // Arbre d'eau : il signale les rives depuis loin, avant même que l'eau ne soit visible.
    biomeWeights: { riverbank: 1, wetland: 0.8 },
    waterProximity: { min: 0.55, max: 1, tolerance: 0.2 },
    moisture: { min: 0.7, max: 1, tolerance: 0.15 },
    slope: { min: 0, max: 0.2, tolerance: 0.12 },
    interactive: true,
    renewalMode: 'none',
  },
  {
    id: 'fern',
    displayName: 'Fougère',
    category: 'ground_cover',
    visual: {
      shape: 'tuft',
      primaryColor: '#4f7a3f',
      heightM: 0.6,
      radiusM: 0.35,
      scaleVariance: 0.4,
      detailOnly: true,
    },
    density: 0.3,
    rarity: 0.8,
    spacingMeters: 2.8,
    clustering: 0.55,
    clusterScaleMeters: 30,
    biomeWeights: { forest: 1, wetland: 0.6, sparse_forest: 0.5 },
    moisture: { min: 0.6, max: 1, tolerance: 0.2 },
    vegetation: { min: 0.6, max: 1, tolerance: 0.2 },
    slope: { min: 0, max: 0.3, tolerance: 0.15 },
    // Décor du sous-bois humide : aucune mécanique ne le manipulera avant longtemps.
    interactive: false,
  },
  {
    id: 'amanita_muscaria',
    displayName: 'Amanite tue-mouches',
    category: 'ground_cover',
    visual: {
      shape: 'mushroom',
      primaryColor: '#b8322a',
      secondaryColor: '#e8e0c8',
      heightM: 0.2,
      radiusM: 0.15,
      scaleVariance: 0.35,
      detailOnly: true,
    },
    density: 0.14,
    // Moins commune que le champignon commun : elle se remarque, elle ne se confond pas.
    rarity: 0.35,
    spacingMeters: 2.4,
    clustering: 0.6,
    clusterScaleMeters: 25,
    biomeWeights: { forest: 1, sparse_forest: 0.5, wetland: 0.2 },
    moisture: { min: 0.6, max: 1, tolerance: 0.2 },
    vegetation: { min: 0.4, max: 1, tolerance: 0.25 },
    slope: { min: 0, max: 0.3, tolerance: 0.15 },
    interactive: true,
    // Intoxication forte : c'est la vérité du monde, pas ce qu'un humain en sait.
    food: { nutritionKcal: 30, waterContent01: 0.9, toxicity01: 0.8 },
    renewalMode: 'regrowWhenDepleted',
  },
  {
    id: 'amanita_phalloides',
    displayName: 'Amanite phalloïde',
    category: 'ground_cover',
    visual: {
      shape: 'mushroom',
      primaryColor: '#a8b078',
      secondaryColor: '#dcd8c0',
      heightM: 0.16,
      radiusM: 0.12,
      scaleVariance: 0.3,
      detailOnly: true,
    },
    density: 0.11,
    // La plus toxique du monde, et la plus discrète : l'erreur serait fatale.
    rarity: 0.3,
    spacingMeters: 2.6,
    clustering: 0.55,
    clusterScaleMeters: 30,
    biomeWeights: { forest: 1, sparse_forest: 0.4 },
    moisture: { min: 0.7, max: 1, tolerance: 0.15 },
    vegetation: { min: 0.6, max: 1, tolerance: 0.2 },
    slope: { min: 0, max: 0.25, tolerance: 0.12 },
    interactive: true,
    food: { nutritionKcal: 25, waterContent01: 0.9, toxicity01: 0.95 },
    renewalMode: 'regrowWhenDepleted',
  },
  {
    id: 'cattail',
    displayName: 'Massette',
    category: 'ground_cover',
    visual: {
      shape: 'reed',
      primaryColor: '#7d8f4a',
      heightM: 1.8,
      radiusM: 0.12,
      scaleVariance: 0.3,
      detailOnly: true,
    },
    density: 0.3,
    rarity: 0.6,
    spacingMeters: 2,
    clustering: 0.6,
    clusterScaleMeters: 20,
    biomeWeights: { wetland: 1, riverbank: 0.6 },
    waterProximity: { min: 0.7, max: 1, tolerance: 0.15 },
    slope: { min: 0, max: 0.1, tolerance: 0.08 },
    interactive: true,
    // Rhizome farineux : l'amidon des marais, comestible toute l'année.
    food: { nutritionKcal: 130, waterContent01: 0.75, toxicity01: 0 },
    renewalMode: 'regrowWhenDepleted',
  },
];
